# Generated by Django 4.2.29 on 2026-05-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileManagement', '0003_useroptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='useroptions',
            name='time_format',
            field=models.CharField(choices=[('24h', '24-hour'), ('12h', '12-hour')], default='24h', max_length=3),
        ),
    ]
