# Generated by Django 4.2.29 on 2026-05-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileManagement', '0004_useroptions_time_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useroptions',
            name='color_theme',
            field=models.CharField(choices=[('forest', 'Forest'), ('midnight', 'Midnight'), ('ember', 'Ember'), ('ocean', 'Ocean'), ('light', 'Light'), ('hxxr', 'Green HXXR'), ('win98', 'Windows 98'), ('doom', 'DOOM'), ('halo3', 'Halo 3')], default='forest', max_length=20),
        ),
    ]
