# Generated by Django 4.2.29 on 2026-05-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileManagement', '0005_alter_useroptions_color_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='useroptions',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Español (Spanish)'), ('zh-hans', '中文 (Chinese Simplified)'), ('fr', 'Français (French)'), ('de', 'Deutsch (German)'), ('ja', '日本語 (Japanese)'), ('pt', 'Português (Portuguese)'), ('ar', 'العربية (Arabic)')], default='en', max_length=10),
        ),
    ]
