# Generated by Django 5.1.6 on 2026-05-31 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileManagement', '0006_add_language_to_useroptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useroptions',
            name='color_theme',
            field=models.CharField(choices=[('forest', 'Forest'), ('midnight', 'Midnight'), ('ember', 'Ember'), ('ocean', 'Ocean'), ('light', 'Light'), ('rose', 'Rose Petal'), ('blush', 'Blush'), ('pearl', 'Pearl'), ('hxxr', 'Green HXXR'), ('win98', 'Windows 98'), ('doom', 'DOOM'), ('halo3', 'Halo 3')], default='forest', max_length=20),
        ),
    ]
